-- 371: discard CAPTURES server-side — the bytes in the bucket.
--
-- WHY. hadar's delete spec: "once it is deleted all of the items (recordings,
-- and images) are being deleted with it -- it is this simple." 369 covers a
-- deleted EXTRA, but a capture deleted before any extra was sent — his exact
-- case: a walkthrough discarded from the gallery — left its media orphaned in
-- the storage bucket forever. Three of his own deleted files sit there now.
-- Local delete without cloud delete is "deleted from this phone", which is a
-- claim the UI already refuses to make; this makes the honest claim the strong
-- one instead.
--
-- SAME SHAPE AS 369, for the same forced reasons: the capture ROW stays
-- (transcripts are append-only, five side-tables carry no cascade), the STORAGE
-- OBJECT goes, and the act lands in the same capture_discarded ledger 369 owns.
--
-- WHAT IT REFUSES — each one is potentially somebody else's evidence:
--   * a capture the caller does not own;
--   * a capture behind ANY decision that ever had a confirmation_request sent.
--     "Ever sent" again, not "sent now": a superseded request still went out
--     and was still read. Refusal is PER CAPTURE and silent-per-row (skipped,
--     counted) rather than aborting the batch: one protected capture must not
--     keep two hundred deletable ones in the bucket.
--
-- OWNERSHIP: only discard_captures_own is created here (check-sql-duplicates);
-- the capture_discarded table belongs to 369.

-- THE FUNCTION MOVED TO 372, and the reason is a platform law found on a real
-- phone: Supabase forbids `delete from storage.objects` in SQL ("Direct
-- deletion from storage tables is not allowed. Use the Storage API instead."),
-- so the version defined HERE failed on every call. 372 keeps every guard and
-- the tombstone, returns the approved object keys, and the CLIENT removes the
-- bytes through the Storage API under 372's own-folder delete policy. This file
-- stays as the record of the attempt; single-ownership says the definition
-- lives in exactly one place, and that place is 372.
