#!/usr/bin/env bash
#
# Publish the public site to GitHub Pages.
#
# WHY THIS EXISTS. The `gh-pages` branch was first built by hand (2026-08-17), which
# means the next person to fix a typo in the privacy policy edits `website/`, sees
# nothing change on the live site, and has no way to know why. A deploy that lives only
# in someone's memory is a deploy that silently stops happening.
#
# WHAT IT DOES
#   website/      → index.html, privacy.html, terms.html      (the public face)
#   apps/web/     → confirm.html, ewa.js                      (the approval page)
#   → committed to the ORPHAN branch `gh-pages` and pushed.
#
# THE BRANCH IS GENERATED. It shares no history with `main` on purpose: it cannot be
# merged in by accident, and a merge could never drag the repo's specs, SQL or mobile
# source onto a public website. Never edit it directly — this script overwrites it.
#
# It uses a temporary WORKTREE rather than switching branches, so it cannot touch or
# stash whatever you have open. Safe to run with a dirty tree.
#
# ── THIS IS NO LONGER THE PUBLISHER [2026-08-25] ─────────────────────────────
#
# GitHub Pages was switched to build_type=workflow. It no longer serves the
# `gh-pages` branch this script writes, so running it publishes nothing — it just
# commits and pushes, greenly, to a branch nobody reads. That is the same silent
# failure this script's own header was written to prevent, one level up.
#
# It also copied apps/web/confirm.html RAW, placeholders and all. That file is the
# reason for the outage that forced the switch: every approval link opened to
# "Invalid supabaseUrl" and hung on Loading, for three days, with no red run
# anywhere. Restoring this script as the publisher would restore that bug.
#
# The publisher is .github/workflows/deploy-confirm-page.yml, which ships all seven
# files, substitutes the Supabase config, and verifies the live URLs afterwards.
# This script is kept for its guards and its history, and refuses to run.
#
# To deploy:   gh workflow run "Deploy public site"
#
# Usage:  ./scripts/deploy-site.sh   (refuses — see above)
set -euo pipefail

if [ "${I_KNOW_PAGES_IGNORES_THIS_BRANCH:-}" != "1" ]; then
  cat >&2 <<'STOP'
refusing: gh-pages is not served any more.

GitHub Pages is on build_type=workflow. Pushing this branch changes nothing on
https://approve.ezchangeorders.com and would look like it worked.

Deploy with:   gh workflow run "Deploy public site"

If you genuinely need to write the branch anyway (archival, or you are moving
Pages back to legacy publishing on purpose), re-run with:
  I_KNOW_PAGES_IGNORES_THIS_BRANCH=1 ./scripts/deploy-site.sh
and fix the confirm.html substitution first — this script copies it raw.
STOP
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BRANCH="gh-pages"
DOMAIN="approve.ezchangeorders.com"
WORK="$(mktemp -d)"
cleanup() { git -C "$ROOT" worktree remove --force "$WORK" 2>/dev/null || true; rm -rf "$WORK"; }
trap cleanup EXIT

cd "$ROOT"

# REFUSE TO PUBLISH A HALF-SITE. A missing file here is a page that 404s for a carrier
# reviewer or a homeowner, and the deploy would otherwise "succeed" quietly.
for f in website/index.html website/privacy.html website/terms.html \
         apps/web/confirm.html apps/web/ewa.js; do
  [ -f "$f" ] || { echo "missing: $f" >&2; exit 1; }
done

# The three clauses the carriers check. Losing one does not break a page — it revokes
# the campaign, days later, silently, and the app stops being able to text anybody.
# Cheaper to fail here than to find out from a client who never got their change order.
for needle in "never shared or sold" "Message frequency" "Message and data rates may apply"; do
  grep -qi "$needle" website/privacy.html \
    || { echo "privacy.html no longer states: $needle" >&2; exit 1; }
done

echo "→ preparing $BRANCH"
git fetch origin "$BRANCH" --quiet 2>/dev/null || true
if git show-ref --verify --quiet "refs/remotes/origin/$BRANCH"; then
  git worktree add --quiet -B "$BRANCH" "$WORK" "origin/$BRANCH"
else
  git worktree add --quiet --detach "$WORK"
  git -C "$WORK" checkout --quiet --orphan "$BRANCH"
fi

# Clear everything except .git, so a file deleted from source disappears from the site.
find "$WORK" -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

cp website/index.html website/privacy.html website/terms.html "$WORK/"
cp apps/web/confirm.html apps/web/ewa.js "$WORK/"
# Stops GitHub treating these as Jekyll sources, which silently drops any file whose
# name begins with an underscore.
touch "$WORK/.nojekyll"
echo "$DOMAIN" > "$WORK/CNAME"

cd "$WORK"
git add -A
if git diff --cached --quiet; then
  echo "→ already up to date; nothing to publish"
  exit 0
fi
git commit --quiet -m "Publish site $(git -C "$ROOT" rev-parse --short HEAD)

WHY:
  Generated by scripts/deploy-site.sh from website/ and apps/web/. This branch is
  build output, not source — edit the source directories, never this branch.

GOALS:
  The landing page, privacy policy, terms and the no-login approval page are live at
  https://$DOMAIN.

COMPLETION:
  100% for the publish. Whether the pages are CORRECT is the source's business.

BLAST RADIUS:
  Public website only. No app, schema or spec is touched by this branch."
git push --quiet origin "$BRANCH"

echo "→ published to https://$DOMAIN/"
echo "   privacy: https://$DOMAIN/privacy.html"
echo "   terms:   https://$DOMAIN/terms.html"
